### ISSUE TITLE
Round 1 Dev Comments

### ISSUE THREAD

**Issue by jeannieboardpackager** [clearbold/boardpackager#1]
Please change the icon for security as discussed. 

Please adjust any email addresses within the copy to prevent bot emails such as using underscores or a space around any @ –trust your team to know what's best for this, we are not particular to one style or another. 

Thank you!

**Comment by circa1977** [comment]
Thanks, @jeannieboardpackager! I've moved this into 2 distinct tickets, so I'll close this one out. We prefer 1 item per ticket so that they can be assigned, queued, discussed, and closed out distinctly.

If a ticket is QA-based or a bug, please be sure to include:

* Browser
* What you expected to see happen
* What happened instead

Thanks!
